module.exports = {
    words: ["eminem", "stan", "mom's spaghetti", "toy soldiers", "slim shady", "8 mile", "d12", "marshall mathers", "my salsa", "venom", "hayley", "debbie", "summa lumma dooma lumma",
        "oranges, peaches, pears, syringes",
        "hello, i'm quite mellow, a white fellow", "swag juice", "cleaning out my closet", "dear slim", "success is my only motherf*****g option, failure's not", "not afraid", "my band",
        "survival", "revenge", "What she tripped, fell, landed on his dick?", "No, dad! I said no! I don't need no help peeing! I'm a big boy, I can do it by myself, see?", "I only get naked when the babysitter tells me. She showed me a movie like night mare on elm street", "dada?", "BLEEEDD BITCH BLEEDD", "I haaaaaate you", "Two trailer park girls", "Chubba chubba chubba chubba chubba chubbie", "I don't have any lines to go right here so, chubba teletubbie!", "Fella's (WHAT?!) Fella's (WHAT?!)", "Grab your left nut, make your right one jealous (what?)",
        "Hey, it's me, Versace", "Whoops, somebody shot me!", "Right, Ken? Give me an amen (AAA-men!)", "You can't reach me, my mom can't neither", "Dr. Dre? (What up?)", "I spit when I talk, I fuck anything that walks (cm'ere)", "Will Smith don't have to cuss in his raps to sell records,", "well I do, so fuck him and fuck you too!", "I got 99 problems and a bitch ain't one, she's all 99 of them I need a machine gun", "Beef with me I'mma even the score equally", "take you on Jerry Springer and beat your ass legally",
        "See that gerbil ? grab that tube...", "I think I smell the scent of a placenta", "But Slim, what if you win, wouldn't it be weird", "Yeah he's cute, but I think he's married to Kim, hee-hee", "there's a million of us just like me", "I guess I'm a CRIMINAL!", "Purple Pills", "chicka chicka", "my name is", "shady made me",
        "I think Kim Kardashian's a man", "They call me superman", "Squeeze it, squish it then pass it to her friend", "Little hellions kids feeling rebellious", "'till someone comes along on a mission and yells BIIIIITCH'", "Guess who's back?", "Meet Eddie, twenty-three years old", "Guess who's back with a brand new rap", "Lose it", "Guess who's back with a brand new rap",
        "Go Go Gadget Dick!", "Fuck you Debbie", "How you gonna breastfeed me mom, you ain't got no tits!", "Life is no nintendo game", "Don't take me for a joke, I'm no comedian", "Kamikaze", "Stepping Stone", "I'm driving a Porsche over the floorboards"
    ]
}
